version: '3'

services:
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opencellid_db

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: /code/entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes: 
      - ./nginx/:/etc/nginx/conf.d
      - ./logs/:/code/logs
    ports: 
      - "80:80"
    links:
      - web

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./scraper:/scraper
    command: sh -c "python3 scraper.py"