# Generated by Django 2.2.6 on 2019-10-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencellid',
            name='averageSignal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='changeable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='radio',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opencellid',
            name='updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opencellid',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opencellid',
            name='cell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opencellid',
            name='mcc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opencellid',
            name='net',
            field=models.IntegerField(default=0),
        ),
    ]
